import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header/Header";
import Sidebar from "./components/Sidebar/Sidebar";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { NextUIProvider } from "@nextui-org/react";
import { Inter } from "next/font/google";
import { context } from "./contextProvider";
import contextProvider from "./contextProvider";
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased`}
      >
        <NextUIProvider>
          <contextProvider>
            <Header />
            <Sidebar />
            <div className="childrenWrapper">{children}</div>
          </contextProvider>
        </NextUIProvider>
      </body>
    </html>
  );
}


